In [1145]:
import pandas as pd

In [1152]:
fertility = pd.read_csv("C:/Downloads/Fertility_sum.csv")
eu = pd.read_csv("C:/Downloads/data_filter/eu_country.csv")

In [1153]:
fertility.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,FREQ,Fréquence d'observation,TERRITORIAL_LEVEL,Niveau territorial,REF_AREA,Zone de référence,...,OBS_VALUE,Valeur d'observation,COUNTRY,Pays,OBS_STATUS,Statut d'observation,UNIT_MULT,Multiplicateur d'unité,DECIMALS,Décimales
0,DATAFLOW,OECD.CFE.EDS:DSD_REG_DEMO@DF_FERTILITY(2.4),Fécondité - Régions,I,A,Annuelle,TL3,Petite région (TL3),DEB22,Bernkastel-Wittlich,...,1200.0,NaN,DEU,Allemagne,A,Valeur normale,0,Units,0,Zero
1,DATAFLOW,OECD.CFE.EDS:DSD_REG_DEMO@DF_FERTILITY(2.4),Fécondité - Régions,I,A,Annuelle,TL3,Petite région (TL3),DE21L,Starnberg,...,1200.0,NaN,DEU,Allemagne,A,Valeur normale,0,Units,0,Zero
2,DATAFLOW,OECD.CFE.EDS:DSD_REG_DEMO@DF_FERTILITY(2.4),Fécondité - Régions,I,A,Annuelle,TL3,Petite région (TL3),DEG0M,Altenburger Land,...,1200.0,NaN,DEU,Allemagne,A,Valeur normale,0,Units,0,Zero
3,DATAFLOW,OECD.CFE.EDS:DSD_REG_DEMO@DF_FERTILITY(2.4),Fécondité - Régions,I,A,Annuelle,TL3,Petite région (TL3),DE21G,Mühldorf a. Inn,...,1200.0,NaN,DEU,Allemagne,A,Valeur normale,0,Units,0,Zero
4,DATAFLOW,OECD.CFE.EDS:DSD_REG_DEMO@DF_FERTILITY(2.4),Fécondité - Régions,I,A,Annuelle,TL3,Petite région (TL3),DE737,Werra-Meißner-Kreis,...,1200.0,NaN,DEU,Allemagne,A,Valeur normale,0,Units,0,Zero

In [1154]:
fertility.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'ACTION', 'FREQ',
       'Fréquence d'observation', 'TERRITORIAL_LEVEL', 'Niveau territorial',
       'REF_AREA', 'Zone de référence', 'TERRITORIAL_TYPE',
       'Typologie territoriale', 'MEASURE', 'Mesure', 'AGE', 'Âge', 'SEX',
       'Sexe', 'UNIT_MEASURE', 'Unité de mesure', 'TIME_PERIOD',
       'Période temporelle', 'OBS_VALUE', 'Valeur d'observation', 'COUNTRY',
       'Pays', 'OBS_STATUS', 'Statut d'observation', 'UNIT_MULT',
       'Multiplicateur d'unité', 'DECIMALS', 'Décimales'],
      dtype='object')

In [1155]:
cols_keep = [
    "TIME_PERIOD",
    "REF_AREA", # code area
    "Zone de référence",
    "COUNTRY", # code country
    "Pays", # name country
    "TERRITORIAL_LEVEL", # level of area
    "MEASURE",
    "Unité de mesure",
    "AGE",
    "SEX",
    "OBS_VALUE", # VALUE

]

In [1156]:
fertility_eu = fertility[cols_keep].copy()
fertility_eu

,TIME_PERIOD,REF_AREA,Zone de référence,COUNTRY,Pays,TERRITORIAL_LEVEL,MEASURE,Unité de mesure,AGE,SEX,OBS_VALUE
0,1990,DEB22,Bernkastel-Wittlich,DEU,Allemagne,TL3,LIVE_BIRTHS,Naissances,Y0,_T,1200.000
1,1990,DE21L,Starnberg,DEU,Allemagne,TL3,LIVE_BIRTHS,Naissances,Y0,_T,1200.000
2,1990,DEG0M,Altenburger Land,DEU,Allemagne,TL3,LIVE_BIRTHS,Naissances,Y0,_T,1200.000
3,1990,DE21G,Mühldorf a. Inn,DEU,Allemagne,TL3,LIVE_BIRTHS,Naissances,Y0,_T,1200.000
4,1990,DE737,Werra-Meißner-Kreis,DEU,Allemagne,TL3,LIVE_BIRTHS,Naissances,Y0,_T,1200.000
...,...,...,...,...,...,...,...,...,...,...,...
400393,2017,EU27_2020,UE-27,EU27_2020,Union européenne (27 pays à partir du 01/02/2020),CTRY,LIVE_BIRTHS,Pour 1 000 habitants,Y0,_T,9.733
400394,2018,EU27_2020,UE-27,EU27_2020,Union européenne (27 pays à partir du 01/02/2020),CTRY,LIVE_BIRTHS,Pour 1 000 habitants,Y0,_T,9.531
400395,2018,EU27_2020,UE-27,EU27_2020,Union européenne (27 pays à partir du 01/02/2020),CTRY,LIVE_BIRTHS,Naissances,Y0,_T,4244353.000
400396,2019,EU27_2020,UE-27,EU27_2020,Union européenne (27 pays à partir du 01/02/2020),CTRY,LIVE_BIRTHS,Naissances,Y0,_T,4166236.000
400397,2019,EU27_2020,UE-27,EU27_2020,Union européenne (27 pays à partir du 01/02/2020),CTRY,LIVE_BIRTHS,Pour 1 000 habitants,Y0,_T,9.338

In [1157]:

cols_name = {
    "TIME_PERIOD" : "Year",
    "REF_AREA" : "REF_REGION",
    "Zone de référence" : "Area",
    "AGE" : "Age",
    "SEX" : "Sex",
    "COUNTRY":"REF_AREA",
    "Pays" : "Country",
    "TERRITORIAL_LEVEL" : "Level",
    "Unité de mesure" : "Unit_measure",
    "MEASURE" :"Measure",
    "OBS_VALUE" : "Value"
}

In [1158]:
fertility_eu = fertility_eu.rename(columns= cols_name)
fertility_eu

,Year,REF_REGION,Area,REF_AREA,Country,Level,Measure,Unit_measure,Age,Sex,Value
0,1990,DEB22,Bernkastel-Wittlich,DEU,Allemagne,TL3,LIVE_BIRTHS,Naissances,Y0,_T,1200.000
1,1990,DE21L,Starnberg,DEU,Allemagne,TL3,LIVE_BIRTHS,Naissances,Y0,_T,1200.000
2,1990,DEG0M,Altenburger Land,DEU,Allemagne,TL3,LIVE_BIRTHS,Naissances,Y0,_T,1200.000
3,1990,DE21G,Mühldorf a. Inn,DEU,Allemagne,TL3,LIVE_BIRTHS,Naissances,Y0,_T,1200.000
4,1990,DE737,Werra-Meißner-Kreis,DEU,Allemagne,TL3,LIVE_BIRTHS,Naissances,Y0,_T,1200.000
...,...,...,...,...,...,...,...,...,...,...,...
400393,2017,EU27_2020,UE-27,EU27_2020,Union européenne (27 pays à partir du 01/02/2020),CTRY,LIVE_BIRTHS,Pour 1 000 habitants,Y0,_T,9.733
400394,2018,EU27_2020,UE-27,EU27_2020,Union européenne (27 pays à partir du 01/02/2020),CTRY,LIVE_BIRTHS,Pour 1 000 habitants,Y0,_T,9.531
400395,2018,EU27_2020,UE-27,EU27_2020,Union européenne (27 pays à partir du 01/02/2020),CTRY,LIVE_BIRTHS,Naissances,Y0,_T,4244353.000
400396,2019,EU27_2020,UE-27,EU27_2020,Union européenne (27 pays à partir du 01/02/2020),CTRY,LIVE_BIRTHS,Naissances,Y0,_T,4166236.000
400397,2019,EU27_2020,UE-27,EU27_2020,Union européenne (27 pays à partir du 01/02/2020),CTRY,LIVE_BIRTHS,Pour 1 000 habitants,Y0,_T,9.338

In [1159]:
fertility_eu["Age"].unique()

array(['Y0', 'Y_LT5', 'Y25T29', 'Y30T34', 'Y20T24', 'Y35T39', 'Y15T19',
       'Y40T44', 'Y45T49', '_T'], dtype=object)

In [1160]:
fertility_eu["Sex"].unique()

array(['_T', 'F'], dtype=object)

In [1161]:
fertility_eu["Measure"].unique()

array(['LIVE_BIRTHS', 'CHILD_TO_W_RATIO', 'FERT_RATIO'], dtype=object)

In [1162]:
fertility_eu["Age"].unique()

array(['Y0', 'Y_LT5', 'Y25T29', 'Y30T34', 'Y20T24', 'Y35T39', 'Y15T19',
       'Y40T44', 'Y45T49', '_T'], dtype=object)

In [1163]:
#code filter
year = (fertility_eu["Year"] >= 2000) & (fertility_eu["Year"] <= 2021)
fertility_eu = fertility_eu[year]
fertility_eu = fertility_eu[fertility_eu["REF_AREA"].isin(eu["REF_AREA"])]

# Fertility and birth rate (level Country and Area)
fertility_area = fertility_eu.copy()
birth_rate_condition = (fertility_area["Measure"] == "LIVE_BIRTHS") & (fertility_area["Age"] == "Y0") & (fertility_area["Sex"] == "_T") & (fertility_area["Unit_measure"] == "Pour 1 000 habitants")
fertility_condition = (fertility_area["Measure"] == "FERT_RATIO") & (fertility_area["Age"] == "_T")
fertility_area = fertility_area[fertility_condition | birth_rate_condition]

fertility_area.drop(columns= ["Age","Sex","Unit_measure"],inplace = True)
# birth rate


birth_age = fertility_eu["Age"] == "Y0"
total_sex = fertility_eu["Sex"] == "_T"
birth_rate_eu = fertility_eu[total_sex & birth_age]

# fertility
fertility_eu = fertility_eu[fertility_eu["Measure"] == "FERT_RATIO"]
total_age = fertility_eu["Age"] == "_T"
fertility_eu = fertility_eu[total_age]

In [1164]:
fertility_area

,Year,REF_REGION,Area,REF_AREA,Country,Level,Measure,Value
14295,2006,DEB22,Bernkastel-Wittlich,DEU,Allemagne,TL3,LIVE_BIRTHS,7.608
14296,2006,DEA38,Warendorf,DEU,Allemagne,TL3,LIVE_BIRTHS,8.811
14297,2006,DE40G,Spree-Neiße,DEU,Allemagne,TL3,LIVE_BIRTHS,6.005
14298,2006,DEB3F,"Kaiserslautern, Landkreis",DEU,Allemagne,TL3,LIVE_BIRTHS,7.482
14299,2006,DE148,Ravensburg,DEU,Allemagne,TL3,LIVE_BIRTHS,8.942
...,...,...,...,...,...,...,...,...
400379,2012,SK032,Région de Banská Bystrica,SVK,République slovaque,TL3,LIVE_BIRTHS,9.156
400380,2012,SK042,Région de Košice,SVK,République slovaque,TL3,LIVE_BIRTHS,11.221
400382,2012,SK023,Région de Nitra,SVK,République slovaque,TL3,LIVE_BIRTHS,8.726
400386,2012,SK041,Région de Prešov,SVK,République slovaque,TL3,LIVE_BIRTHS,11.711
400387,2012,SK021,Région de Trnava,SVK,République slovaque,TL3,LIVE_BIRTHS,9.519

In [1165]:
birth_rate_eu["Unit_measure"].unique()

array(['Naissances', 'Pour 1 000 habitants'], dtype=object)

In [1166]:
fertility_eu["Unit_measure"].unique()

array(['Naissances vivantes par femme'], dtype=object)

In [1167]:
country = birth_rate_eu["Level"] == "CTRY"

birth_rate_eu = birth_rate_eu[country]
Per_1000_inhabitants = birth_rate_eu["Unit_measure"] == "Pour 1 000 habitants"
birth_rate_eu = birth_rate_eu[Per_1000_inhabitants]

birth_rate_eu.dropna(subset= "Value",inplace= True)
birth_rate_eu.drop(columns= ["Age","Sex","Unit_measure"],inplace = True)

In [1168]:
country = fertility_eu["Level"] == "CTRY"
fertility_eu = fertility_eu[country]
fertility_eu.dropna(subset= "Value",inplace= True)
fertility_eu.drop(columns= ["Age","Sex","Unit_measure"],inplace = True)

In [1169]:
print(f"fertility : ", len(fertility_eu["Country"].unique()))
print(f"birth rate : ", len(birth_rate_eu["Country"].unique()))

print(f"fertility year : ", len(fertility_eu["Year"].unique()))
print(f"birth rate year : ", len(birth_rate_eu["Year"].unique()))

fertility :  28
birth rate :  28
fertility year :  22
birth rate year :  22

In [1170]:
birth_rate_eu[birth_rate_eu["Year"] == 2000]

,Year,REF_REGION,Area,REF_AREA,Country,Level,Measure,Value
146316,2000,ISL,Islande,ISL,Islande,CTRY,LIVE_BIRTHS,15.463
146318,2000,LUX,Luxembourg,LUX,Luxembourg,CTRY,LIVE_BIRTHS,13.199
146320,2000,DEU,Allemagne,DEU,Allemagne,CTRY,LIVE_BIRTHS,9.335
146321,2000,SVK,République slovaque,SVK,République slovaque,CTRY,LIVE_BIRTHS,10.216
146322,2000,ESP,Espagne,ESP,Espagne,CTRY,LIVE_BIRTHS,9.825
146323,2000,SWE,Suède,SWE,Suède,CTRY,LIVE_BIRTHS,10.206
146325,2000,HRV,Croatie,HRV,Croatie,CTRY,LIVE_BIRTHS,9.726
146326,2000,LVA,Lettonie,LVA,Lettonie,CTRY,LIVE_BIRTHS,8.524
146327,2000,GRC,Grèce,GRC,Grèce,CTRY,LIVE_BIRTHS,9.583
146330,2000,CHE,Suisse,CHE,Suisse,CTRY,LIVE_BIRTHS,10.951
146331,2000,EST,Estonie,EST,Estonie,CTRY,LIVE_BIRTHS,9.325
146333,2000,BEL,Belgique,BEL,Belgique,CTRY,LIVE_BIRTHS,11.368
146334,2000,IRL,Irlande,IRL,Irlande,CTRY,LIVE_BIRTHS,14.504
146335,2000,NOR,Norvège,NOR,Norvège,CTRY,LIVE_BIRTHS,13.226
146336,2000,AUT,Autriche,AUT,Autriche,CTRY,LIVE_BIRTHS,9.781
146337,2000,FIN,Finlande,FIN,Finlande,CTRY,LIVE_BIRTHS,10.972
146339,2000,ROU,Roumanie,ROU,Roumanie,CTRY,LIVE_BIRTHS,10.444
146341,2000,SVN,Slovénie,SVN,Slovénie,CTRY,LIVE_BIRTHS,9.146
146342,2000,ITA,Italie,ITA,Italie,CTRY,LIVE_BIRTHS,9.542
146344,2000,BGR,Bulgarie,BGR,Bulgarie,CTRY,LIVE_BIRTHS,8.995
146346,2000,PRT,Portugal,PRT,Portugal,CTRY,LIVE_BIRTHS,11.709
146349,2000,HUN,Hongrie,HUN,Hongrie,CTRY,LIVE_BIRTHS,9.548
146350,2000,DNK,Danemark,DNK,Danemark,CTRY,LIVE_BIRTHS,12.586
146351,2000,NLD,Pays-Bas,NLD,Pays-Bas,CTRY,LIVE_BIRTHS,13.024
146352,2000,GBR,Royaume-Uni,GBR,Royaume-Uni,CTRY,LIVE_BIRTHS,11.526
146353,2000,LTU,Lituanie,LTU,Lituanie,CTRY,LIVE_BIRTHS,9.723
146355,2000,FRA,France,FRA,France,CTRY,LIVE_BIRTHS,13.326
146356,2000,POL,Pologne,POL,Pologne,CTRY,LIVE_BIRTHS,9.888

In [1171]:
fertility_eu[fertility_eu["Year"] == 2000]

,Year,REF_REGION,Area,REF_AREA,Country,Level,Measure,Value
350062,2000,FRA,France,FRA,France,CTRY,FERT_RATIO,1.89
350067,2000,NOR,Norvège,NOR,Norvège,CTRY,FERT_RATIO,1.85
350068,2000,EST,Estonie,EST,Estonie,CTRY,FERT_RATIO,1.36
350069,2000,CHE,Suisse,CHE,Suisse,CTRY,FERT_RATIO,1.50
350070,2000,GBR,Royaume-Uni,GBR,Royaume-Uni,CTRY,FERT_RATIO,1.48
350071,2000,PRT,Portugal,PRT,Portugal,CTRY,FERT_RATIO,1.55
350073,2000,IRL,Irlande,IRL,Irlande,CTRY,FERT_RATIO,1.89
350074,2000,POL,Pologne,POL,Pologne,CTRY,FERT_RATIO,1.37
350075,2000,FIN,Finlande,FIN,Finlande,CTRY,FERT_RATIO,1.73
350076,2000,BGR,Bulgarie,BGR,Bulgarie,CTRY,FERT_RATIO,1.26
350077,2000,GRC,Grèce,GRC,Grèce,CTRY,FERT_RATIO,1.25
350079,2000,SWE,Suède,SWE,Suède,CTRY,FERT_RATIO,1.54
350080,2000,DEU,Allemagne,DEU,Allemagne,CTRY,FERT_RATIO,1.38
350082,2000,DNK,Danemark,DNK,Danemark,CTRY,FERT_RATIO,1.77
350083,2000,LTU,Lituanie,LTU,Lituanie,CTRY,FERT_RATIO,1.39
350084,2000,HUN,Hongrie,HUN,Hongrie,CTRY,FERT_RATIO,1.32
350085,2000,ITA,Italie,ITA,Italie,CTRY,FERT_RATIO,1.26
350086,2000,ROU,Roumanie,ROU,Roumanie,CTRY,FERT_RATIO,1.31
350087,2000,AUT,Autriche,AUT,Autriche,CTRY,FERT_RATIO,1.36
350088,2000,ESP,Espagne,ESP,Espagne,CTRY,FERT_RATIO,1.22
350089,2000,ISL,Islande,ISL,Islande,CTRY,FERT_RATIO,2.08
350090,2000,SVK,République slovaque,SVK,République slovaque,CTRY,FERT_RATIO,1.30
350091,2000,SVN,Slovénie,SVN,Slovénie,CTRY,FERT_RATIO,1.26
350093,2000,NLD,Pays-Bas,NLD,Pays-Bas,CTRY,FERT_RATIO,1.72
350094,2000,LUX,Luxembourg,LUX,Luxembourg,CTRY,FERT_RATIO,1.76
350095,2000,LVA,Lettonie,LVA,Lettonie,CTRY,FERT_RATIO,1.25
350096,2000,BEL,Belgique,BEL,Belgique,CTRY,FERT_RATIO,1.67

In [1172]:
fertility_eu.groupby(["Year"])["Country"].nunique()

Year
2000    27
2001    28
2002    28
2003    28
2004    28
2005    28
2006    28
2007    28
2008    28
2009    28
2010    28
2011    27
2012    27
2013    28
2014    28
2015    28
2016    28
2017    28
2018    28
2019    28
2020    28
2021    28
Name: Country, dtype: int64

In [1173]:
birth_rate_eu.groupby(["Year"])["Country"].nunique()

Year
2000    28
2001    28
2002    28
2003    28
2004    28
2005    28
2006    28
2007    28
2008    28
2009    28
2010    28
2011    28
2012    28
2013    28
2014    28
2015    28
2016    28
2017    28
2018    28
2019    28
2020    28
2021    28
Name: Country, dtype: int64

In [1175]:
# birth_rate_eu.to_csv("C:/Downloads/data_filter/birth_rate.csv",index= False)
# fertility_eu.to_csv("C:/Downloads/data_filter/fertility.csv",index= False)
fertility_area.to_csv("C:/Downloads/data_filter/fertility_area.csv",index= False)