In [88]:
import pandas as pd

In [89]:
credits = pd.read_csv(r"C:/Downloads/new_data/tiết kiệm và nợ của hộ gia đình.csv")
eu_regions = pd.read_csv(r"C:/Downloads/new_data/eu_country.csv")
credits.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,FREQ,Fréquence d'observation,REF_AREA,Zone de référence,MEASURE,Mesure,...,CONF_STATUS,Statut de confidentialité,DECIMALS,Décimales,OBS_STATUS,Statut d'observation,UNIT_MULT,Multiplicateur d'unité,CURRENCY,Monnaie
0,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG(1.0),NAAG,I,A,Annuelle,AUS,Australie,P31S1M_CP04,Consommation en logement des ménages et des IS...,...,F,Libre (libre pour publication),2,Two,A,Valeur normale,0,Units,_Z,N'est pas applicable
1,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG(1.0),NAAG,I,A,Annuelle,AUT,Autriche,P31S1M_CP04,Consommation en logement des ménages et des IS...,...,F,Libre (libre pour publication),2,Two,A,Valeur normale,0,Units,_Z,N'est pas applicable
2,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG(1.0),NAAG,I,A,Annuelle,BEL,Belgique,P31S1M_CP04,Consommation en logement des ménages et des IS...,...,F,Libre (libre pour publication),2,Two,A,Valeur normale,0,Units,_Z,N'est pas applicable
3,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG(1.0),NAAG,I,A,Annuelle,CZE,Tchéquie,P31S1M_CP04,Consommation en logement des ménages et des IS...,...,F,Libre (libre pour publication),2,Two,A,Valeur normale,0,Units,_Z,N'est pas applicable
4,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG(1.0),NAAG,I,A,Annuelle,DNK,Danemark,P31S1M_CP04,Consommation en logement des ménages et des IS...,...,F,Libre (libre pour publication),2,Two,A,Valeur normale,0,Units,_Z,N'est pas applicable

In [90]:
credits.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'ACTION', 'FREQ',
       'Fréquence d'observation', 'REF_AREA', 'Zone de référence', 'MEASURE',
       'Mesure', 'UNIT_MEASURE', 'Unité de mesure', 'CHAPTER', 'Chapitre',
       'TIME_PERIOD', 'Période temporelle', 'OBS_VALUE',
       'Valeur d'observation', 'ADJUSTMENT', 'Ajustement', 'COUNTERPART_AREA',
       'Zone de contrepartie', 'SECTOR', 'Secteur institutionnel',
       'COUNTERPART_SECTOR', 'Secteur institutionnel de contrepartie',
       'CONSOLIDATION', 'Statut de consolidation', 'ACCOUNTING_ENTRY',
       'Ecriture comptable', 'TRANSACTION', 'Transaction', 'INSTR_ASSET',
       'Instruments et actifs', 'MATURITY', 'Échéance initiale et résiduelle',
       'PRODUCT', 'Produit', 'PENSION_FUNDTYPE', 'Type de fond de pension',
       'CURRENCY_DENOM', 'Monnaie de libellé', 'VALUATION', 'Evaluation',
       'PRICE_BASE', 'Type de prix', 'TRANSFORMATION', 'Transformation',
       'TABLE_IDENTIFIER', 'Identifiant de tableau', 'REF_YEAR_PRICE',
       'Prix ​​année de référence', 'BASE_PER', 'Période de base',
       'CONF_STATUS', 'Statut de confidentialité', 'DECIMALS', 'Décimales',
       'OBS_STATUS', 'Statut d'observation', 'UNIT_MULT',
       'Multiplicateur d'unité', 'CURRENCY', 'Monnaie'],
      dtype='object')

In [91]:
cols_keep = [
    "TIME_PERIOD",
    "REF_AREA",
    "Zone de référence",
    "Mesure",
    "UNIT_MEASURE",
    "OBS_VALUE",
]

In [92]:
test = credits[cols_keep]
test

,TIME_PERIOD,REF_AREA,Zone de référence,Mesure,UNIT_MEASURE,OBS_VALUE
0,2000,AUS,Australie,Consommation en logement des ménages et des IS...,PT_B7N_S1M,16.180402
1,2000,AUT,Autriche,Consommation en logement des ménages et des IS...,PT_B7N_S1M,14.638621
2,2000,BEL,Belgique,Consommation en logement des ménages et des IS...,PT_B7N_S1M,15.273736
3,2000,CZE,Tchéquie,Consommation en logement des ménages et des IS...,PT_B7N_S1M,18.336961
4,2000,DNK,Danemark,Consommation en logement des ménages et des IS...,PT_B7N_S1M,20.919383
...,...,...,...,...,...,...
3810,2024,KOR,Corée,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,58000.093184
3811,2024,NLD,Pays-Bas,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,90174.489987
3812,2024,SVK,République slovaque,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,57834.808275
3813,2024,SVN,Slovénie,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,48095.551213
3814,2024,SWE,Suède,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,43970.362519

In [93]:
rename_map = {
    "Zone de référence": "Country",
    "TIME_PERIOD": "Year",
    "Mesure": "Measure",
    "UNIT_MEASURE": "Unit_measure",
    "OBS_VALUE": "Value"
}

test = test.rename(columns=rename_map)
test

,Year,REF_AREA,Country,Measure,Unit_measure,Value
0,2000,AUS,Australie,Consommation en logement des ménages et des IS...,PT_B7N_S1M,16.180402
1,2000,AUT,Autriche,Consommation en logement des ménages et des IS...,PT_B7N_S1M,14.638621
2,2000,BEL,Belgique,Consommation en logement des ménages et des IS...,PT_B7N_S1M,15.273736
3,2000,CZE,Tchéquie,Consommation en logement des ménages et des IS...,PT_B7N_S1M,18.336961
4,2000,DNK,Danemark,Consommation en logement des ménages et des IS...,PT_B7N_S1M,20.919383
...,...,...,...,...,...,...
3810,2024,KOR,Corée,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,58000.093184
3811,2024,NLD,Pays-Bas,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,90174.489987
3812,2024,SVK,République slovaque,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,57834.808275
3813,2024,SVN,Slovénie,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,48095.551213
3814,2024,SWE,Suède,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,43970.362519

In [94]:
eu_country = test["REF_AREA"].isin(eu_regions["REF_AREA"])
test = test[eu_country]
test

,Year,REF_AREA,Country,Measure,Unit_measure,Value
1,2000,AUT,Autriche,Consommation en logement des ménages et des IS...,PT_B7N_S1M,14.638621
2,2000,BEL,Belgique,Consommation en logement des ménages et des IS...,PT_B7N_S1M,15.273736
4,2000,DNK,Danemark,Consommation en logement des ménages et des IS...,PT_B7N_S1M,20.919383
5,2000,EST,Estonie,Consommation en logement des ménages et des IS...,PT_B7N_S1M,19.617102
6,2000,FIN,Finlande,Consommation en logement des ménages et des IS...,PT_B7N_S1M,18.346543
...,...,...,...,...,...,...
3809,2024,DEU,Allemagne,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,126575.249471
3811,2024,NLD,Pays-Bas,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,90174.489987
3812,2024,SVK,République slovaque,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,57834.808275
3813,2024,SVN,Slovénie,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,48095.551213
3814,2024,SWE,Suède,Logements par tête des ménages et des ISBLSM,USD_PPP_PS,43970.362519

In [95]:
test["Measure"].unique()

array(['Consommation en logement des ménages et des ISBLSM',
       'Épargne nette des ménages et des ISBLSM',
       'Dette des ménages et des ISBLSM',
       'Terrains par tête des ménages et des ISBLSM',
       'Logements par tête des ménages et des ISBLSM'], dtype=object)

In [96]:
measure_map = {
    "Dette des ménages et des ISBLSM": "household_debt",
    "Épargne nette des ménages et des ISBLSM": "household_net_saving",
    "Terrains par tête des ménages et des ISBLSM": "land_per_capita"
}

test["Measure"] = test["Measure"].replace(measure_map)
test = test[test["Measure"].isin(measure_map.values())]
test

C:\Users\dhoan\AppData\Local\Temp\ipykernel_2752\4134907532.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Measure"] = test["Measure"].replace(measure_map)

,Year,REF_AREA,Country,Measure,Unit_measure,Value
708,2000,AUT,Autriche,household_net_saving,PT_B6N_S1M,11.750229
709,2000,BEL,Belgique,household_net_saving,PT_B6N_S1M,11.450031
712,2000,DNK,Danemark,household_net_saving,PT_B6N_S1M,-6.572168
713,2000,EST,Estonie,household_net_saving,PT_B6N_S1M,0.000000
714,2000,FIN,Finlande,household_net_saving,PT_B6N_S1M,2.681889
...,...,...,...,...,...,...
3058,2024,IRL,Irlande,land_per_capita,USD_PPP_PS,98007.653722
3060,2024,NLD,Pays-Bas,land_per_capita,USD_PPP_PS,142353.460490
3061,2024,SVK,République slovaque,land_per_capita,USD_PPP_PS,22537.825223
3062,2024,SVN,Slovénie,land_per_capita,USD_PPP_PS,92761.610550
3063,2024,SWE,Suède,land_per_capita,USD_PPP_PS,64995.090768

In [97]:
test["Unit_measure"].unique()

array(['PT_B6N_S1M', 'USD_PPP_PS'], dtype=object)

In [98]:
map = {"PT_B6N_S1M" : "PT", "USD_PPP_PS" : "USD_PPP"}
test["Unit_measure"] = test["Unit_measure"].replace(map)
test

C:\Users\dhoan\AppData\Local\Temp\ipykernel_2752\3284280013.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Unit_measure"] = test["Unit_measure"].replace(map)

,Year,REF_AREA,Country,Measure,Unit_measure,Value
708,2000,AUT,Autriche,household_net_saving,PT,11.750229
709,2000,BEL,Belgique,household_net_saving,PT,11.450031
712,2000,DNK,Danemark,household_net_saving,PT,-6.572168
713,2000,EST,Estonie,household_net_saving,PT,0.000000
714,2000,FIN,Finlande,household_net_saving,PT,2.681889
...,...,...,...,...,...,...
3058,2024,IRL,Irlande,land_per_capita,USD_PPP,98007.653722
3060,2024,NLD,Pays-Bas,land_per_capita,USD_PPP,142353.460490
3061,2024,SVK,République slovaque,land_per_capita,USD_PPP,22537.825223
3062,2024,SVN,Slovénie,land_per_capita,USD_PPP,92761.610550
3063,2024,SWE,Suède,land_per_capita,USD_PPP,64995.090768

In [99]:
test = test.dropna(subset = "Value")

In [100]:
test["Value"] = test["Value"].round(2) 
test

,Year,REF_AREA,Country,Measure,Unit_measure,Value
708,2000,AUT,Autriche,household_net_saving,PT,11.75
709,2000,BEL,Belgique,household_net_saving,PT,11.45
712,2000,DNK,Danemark,household_net_saving,PT,-6.57
713,2000,EST,Estonie,household_net_saving,PT,0.00
714,2000,FIN,Finlande,household_net_saving,PT,2.68
...,...,...,...,...,...,...
3058,2024,IRL,Irlande,land_per_capita,USD_PPP,98007.65
3060,2024,NLD,Pays-Bas,land_per_capita,USD_PPP,142353.46
3061,2024,SVK,République slovaque,land_per_capita,USD_PPP,22537.83
3062,2024,SVN,Slovénie,land_per_capita,USD_PPP,92761.61
3063,2024,SWE,Suède,land_per_capita,USD_PPP,64995.09

In [101]:
measure_sets = (
    test
    .groupby(["Year", "Country"])["Measure"]
    .apply(set)
    .reset_index(name="measures")
)

measure_sets[measure_sets["measures"].apply(len) < 3]

     Year      Country                                measures
8    2000        Grèce  {household_net_saving, household_debt}
12   2000     Lettonie  {household_net_saving, household_debt}
13   2000     Lituanie       {household_debt, land_per_capita}
21   2000     Slovénie       {household_debt, land_per_capita}
22   2000       Suisse  {household_net_saving, household_debt}
..    ...          ...                                     ...
589  2024   Luxembourg  {household_net_saving, household_debt}
591  2024      Pologne  {household_net_saving, household_debt}
592  2024     Portugal  {household_net_saving, household_debt}
593  2024  Royaume-Uni  {household_net_saving, household_debt}
595  2024     Slovénie       {household_debt, land_per_capita}

[117 rows x 3 columns]

In [102]:
test[ (test["Country"] == "Suisse") & (test["Year"] == 2000) ]

      Year REF_AREA Country               Measure Unit_measure   Value
733   2000      CHE  Suisse  household_net_saving           PT   14.56
1590  2000      CHE  Suisse        household_debt           PT  170.42

In [103]:
test

,Year,REF_AREA,Country,Measure,Unit_measure,Value
708,2000,AUT,Autriche,household_net_saving,PT,11.75
709,2000,BEL,Belgique,household_net_saving,PT,11.45
712,2000,DNK,Danemark,household_net_saving,PT,-6.57
713,2000,EST,Estonie,household_net_saving,PT,0.00
714,2000,FIN,Finlande,household_net_saving,PT,2.68
...,...,...,...,...,...,...
3058,2024,IRL,Irlande,land_per_capita,USD_PPP,98007.65
3060,2024,NLD,Pays-Bas,land_per_capita,USD_PPP,142353.46
3061,2024,SVK,République slovaque,land_per_capita,USD_PPP,22537.83
3062,2024,SVN,Slovénie,land_per_capita,USD_PPP,92761.61
3063,2024,SWE,Suède,land_per_capita,USD_PPP,64995.09

In [104]:
test.to_csv("C:/Downloads/data_clean/savings_debt_and_house_prices.csv",index = False)